import { DealItem } from "@/components/Product/BestDealsGrid";

export const bestDeals: DealItem[] = [
  {
    id: 1,
    name: "NIKE Shoe",
    subtitle: "Running Shoe For Men..",
    price: "10,999",
    oldPrice: "20,000",
    discount: "50%",
    image: require("../assets/images/Product/shoe.png"),
    badgeText: "Best Flash Deal",
    badgeColor: "bg-[#26FF91]",
  },
  {
    id: 2,
    name: "Apple Ultra Watch",
    subtitle: "Accurate Measuring Your Health...",
    price: "39,999",
    oldPrice: "20,000",
    discount: "50%",
    image: require("../assets/images/Product/watch.png"),
    badgeText: "Only 1 left",
    textColor: "text-white",
    badgeColor: "bg-[#FF1616]",
  },
  {
    id: 3,
    name: "GOOGLE Pixel 9 Pro",
    subtitle: "8/512 GB , Black Space Color",
    price: "99,999",
    oldPrice: "20,000",
    discount: "50%",
    image: require("../assets/images/Product/Pixel9pro.png"),
    badgeText: "Best Flash Deal",
    badgeColor: "bg-[#26FF91]",
  },
  {
    id: 4,
    name: "Samsung Fridge",
    subtitle: "Accurate Measuring Your Health...",
    price: "39,999",
    oldPrice: "20,000",
    discount: "50%",
    image: require("../assets/images/Product/fridge.png"),
    badgeText: "LYNKD Choice",
    badgeColor: "bg-[#26FF91]",
  },
];
